import type { Metadata } from "next";
import { Noto_Nastaliq_Urdu } from "next/font/google";
import { Noto_Naskh_Arabic } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";

const notoNastaliqUrdu = Noto_Nastaliq_Urdu({
  variable: "--font-nastaliq",
  subsets: ["arabic"],
});

const notoNaskhArabic = Noto_Naskh_Arabic({
  variable: "--font-naskh",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        cz-shortcut-listen="true"
        className={`${notoNastaliqUrdu.variable} ${notoNaskhArabic.variable} antialiased`}
      >
        <Providers>
            {children}
        </Providers>

      </body>
    </html>
  );
}
